import os
import signal
import tempfile
from pathlib import Path

import gradio as gr
import pandas as pd
from PIL import Image

from inference import predict_xray


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

TEST_CSV = Path("data/prepared/test.csv")

# Set this to False before Hugging Face deployment.
LOCAL_DEVELOPMENT_MODE = True


# ---------------------------------------------------------
# Prediction function
# ---------------------------------------------------------

def analyze_xray(image):
    """
    Analyze an uploaded chest X-ray and return:
    1. Class probabilities
    2. Prediction summary
    3. Downloadable text report
    """

    if image is None:
        return (
            {},
            "Please upload or load a chest X-ray image.",
            None,
        )

    try:
        prediction = predict_xray(image)

        probabilities = prediction["probabilities"]
        predicted_label = prediction["predicted_label"]
        confidence = prediction["confidence"]
        device = prediction["device"]

        summary = (
            f"Prediction: {predicted_label}\n"
            f"Confidence: {confidence * 100:.2f}%\n"
            f"Processing device: {device}\n\n"
            "This application is an educational demonstration "
            "and is not intended for clinical diagnosis."
        )

        report_path = create_prediction_report(
            prediction=prediction
        )

        return (
            probabilities,
            summary,
            report_path,
        )

    except Exception as error:
        return (
            {},
            (
                "An error occurred while processing the image:\n"
                f"{error}"
            ),
            None,
        )


# ---------------------------------------------------------
# Create downloadable report
# ---------------------------------------------------------

def create_prediction_report(prediction):
    """
    Create a temporary text file containing prediction results.
    """

    predicted_label = prediction["predicted_label"]
    confidence = prediction["confidence"]
    probabilities = prediction["probabilities"]
    device = prediction["device"]

    report_lines = [
        "Chest X-Ray Classification Assistant",
        "=====================================",
        "",
        f"Prediction: {predicted_label}",
        f"Confidence: {confidence * 100:.2f}%",
        f"Processing device: {device}",
        "",
        "Class Probabilities",
        "-------------------",
    ]

    for label, probability in probabilities.items():
        report_lines.append(
            f"{label}: {probability * 100:.2f}%"
        )

    report_lines.extend(
        [
            "",
            "Educational-Use Notice",
            "----------------------",
            (
                "This result was generated by an experimental "
                "machine-learning model."
            ),
            (
                "It is not a medical diagnosis and must not be used "
                "for clinical decisions."
            ),
        ]
    )

    report_text = "\n".join(report_lines)

    temporary_directory = Path(
        tempfile.gettempdir()
    )

    report_path = (
        temporary_directory
        / "chest_xray_prediction_report.txt"
    )

    report_path.write_text(
        report_text,
        encoding="utf-8",
    )

    return str(report_path)


# ---------------------------------------------------------
# Load an example image
# ---------------------------------------------------------

def load_example():
    """
    Load the first valid image from the prepared test dataset.
    """

    if not TEST_CSV.exists():
        raise gr.Error(
            "The prepared test.csv file was not found."
        )

    dataframe = pd.read_csv(TEST_CSV)

    if dataframe.empty:
        raise gr.Error(
            "The test dataset is empty."
        )

    if "image_path" not in dataframe.columns:
        raise gr.Error(
            "The test dataset does not contain image_path."
        )

    for image_value in dataframe["image_path"]:
        image_path = Path(image_value)

        if image_path.exists():
            with Image.open(image_path) as image:
                return image.convert("RGB")

    raise gr.Error(
        "No valid example image could be found."
    )


# ---------------------------------------------------------
# Clear all results
# ---------------------------------------------------------

def clear_results():
    """
    Reset the application output components.
    """

    return (
        None,
        {},
        "",
        None,
    )


# ---------------------------------------------------------
# Local-only shutdown
# ---------------------------------------------------------

def shutdown_application():
    """
    Stop the local Python process.

    This should not be enabled on Hugging Face Spaces.
    """

    if not LOCAL_DEVELOPMENT_MODE:
        return "Shutdown is disabled in deployment mode."

    print("\nShutdown requested from Gradio.")
    print("Closing the local application...")

    os.kill(
        os.getpid(),
        signal.SIGINT,
    )

    return "Shutting down..."


# ---------------------------------------------------------
# Gradio interface
# ---------------------------------------------------------

with gr.Blocks(
    title="Chest X-Ray Classification Assistant"
) as demo:

    gr.Markdown(
        """
        # Chest X-Ray Classification Assistant

        Upload a frontal chest X-ray to receive a Transformer-based
        **Normal** or **Abnormal** classification.

        The model was fine-tuned using the NIH ChestX-ray14 dataset.

        > **Educational-use notice:** This application is not a medical
        > device and must not be used for diagnosis or treatment.
        """
    )

    with gr.Row():

        # -------------------------------------------------
        # Left side: image and controls
        # -------------------------------------------------

        with gr.Column(scale=1):

            image_input = gr.Image(
                type="pil",
                label="Chest X-Ray Image",
                height=450,
            )

            gr.Markdown("### Control Panel")

            with gr.Row():

                analyze_button = gr.Button(
                    "Analyze",
                    variant="primary",
                )

                example_button = gr.Button(
                    "Load Example",
                )

            with gr.Row():

                clear_button = gr.Button(
                    "Clear",
                )

                shutdown_button = gr.Button(
                    "Shutdown",
                    variant="stop",
                    visible=LOCAL_DEVELOPMENT_MODE,
                )

        # -------------------------------------------------
        # Right side: output and download
        # -------------------------------------------------

        with gr.Column(scale=1):

            probability_output = gr.Label(
                label="Model Probabilities",
                num_top_classes=2,
            )

            summary_output = gr.Textbox(
                label="Prediction Summary",
                lines=8,
                interactive=False,
            )

            download_button = gr.DownloadButton(
                label="Download Prediction Report",
                variant="secondary",
            )

            shutdown_status = gr.Textbox(
                label="Application Status",
                interactive=False,
                visible=LOCAL_DEVELOPMENT_MODE,
            )

    gr.Markdown(
        """
        ## Workflow

        1. Upload an X-ray or select **Load Example**.
        2. Select **Analyze**.
        3. Review the prediction and class probabilities.
        4. Download the result as a text report if needed.
        5. Use **Shutdown** only when running locally.
        """
    )

    # -----------------------------------------------------
    # Button actions
    # -----------------------------------------------------

    analyze_button.click(
        fn=analyze_xray,
        inputs=image_input,
        outputs=[
            probability_output,
            summary_output,
            download_button,
        ],
    )

    example_button.click(
        fn=load_example,
        inputs=[],
        outputs=image_input,
    )

    clear_button.click(
        fn=clear_results,
        inputs=[],
        outputs=[
            image_input,
            probability_output,
            summary_output,
            download_button,
        ],
    )

    shutdown_button.click(
        fn=shutdown_application,
        inputs=[],
        outputs=shutdown_status,
    )


if __name__ == "__main__":
    demo.launch()